# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy Beta Release to Firebase App Distribution"
  lane :deploy do
    gradle(
          task: "bundle",
          build_type: "Release"
    )

    get_version_info
    version_name = lane_context[:version_name]

    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        android_artifact_path: "app/build/outputs/bundle/release/app-release.aab",
        service_credentials_file: "app/firebase_admin.json",
        groups: "me",
        release_notes: ENV["RELEASE_NOTES"],
    )

    slack(
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      username: "Fastlane Bot",
      icon_emoji: ":rocket:",
      channel: "#deployments",
      message: "AOS *#{version_name}* release\n🔗 [Firebase App Distribution](https://console.firebase.google.com/project/#{ENV['FIREBASE_APP_ID']}/appdistribution/releases)\n\n#{ENV['RELEASE_NOTES']}\n"
    )
  end

  private_lane :get_version_info do
    version_name = sh("./gradlew -q printVersionName").strip
    lane_context[:version_name] = version_name
  end
end
