# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy Beta Release to Firebase App Distribution"
  lane :deploy do
    gradle(
          task: "bundle",
          build_type: "Release"
    )

    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        android_artifact_path: "app/build/outputs/bundle/release/app-release.aab",
        service_credentials_file: "app/firebase_admin.json",
        groups: "me",
        release_notes: ENV["RELEASE_NOTES"],
    )
  end
end
